[project]
name = "UniProt-IDMapping"
version = "0.1.0"
description = "Add your description here"
dependencies = [
    "requests >= 2.32.3",
    "numpy    >= 1.26.4",
    "pandas   >= 2.2.2"
]
requires-python = ">= 3.12"

[tool.ruff.format]
quote-style = "preserve"