(:name           "uniprot-idmapping")
(:repo           "taffish-org/uniprot-idmapping")
(:author         "ShishiYuan")
(:version        "1.0.0")
(:intro          "A tool for connecting UniProt.")
(:dependencies)
(:functions      "uniprot-idmapping")
